name: Deploy static content to Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload static content
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./localscenenbackend  # 👈 this is the key change

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
